from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

from autogen_core.models import ChatCompletionClient

from .agbench_config import _read_structured


@dataclass(frozen=True)
class AgBenchSuiteVerificationResult:
    manifest_path: str
    summary_path: str | None
    summary: dict[str, Any]


def verify_agbench_suite(
    *,
    manifest_path: str | Path,
    summary_path: str | Path | None = None,
    load_components: bool = True,
    require_capture_artifacts: bool = False,
    require_provider_artifacts: bool = False,
    require_task_artifacts: bool = False,
) -> AgBenchSuiteVerificationResult:
    manifest_file = Path(manifest_path)
    manifest = _load_json_mapping(manifest_file)
    checks: list[dict[str, Any]] = []
    artifact_status: list[dict[str, Any]] = []

    _check_manifest_shape(manifest, checks)
    variants = manifest.get("config_variants") if isinstance(manifest.get("config_variants"), Mapping) else {}
    for label in ("baseline", "capture", "plugin_rule_only", "plugin_nl_segmentation", "static_capture"):
        _add_check(
            checks,
            name=f"variant:{label}",
            ok=label in variants,
            detail="present" if label in variants else "missing",
            next_step=f"Regenerate the suite so {label}.yaml is present." if label not in variants else None,
        )

    for label, raw_variant in variants.items():
        if not isinstance(raw_variant, Mapping):
            _add_check(checks, name=f"variant:{label}:mapping", ok=False, detail="variant entry is not a mapping")
            continue
        _verify_variant_config(
            label=str(label),
            variant=raw_variant,
            checks=checks,
            load_components=load_components,
        )
        _collect_artifact_status(
            label=str(label),
            variant=raw_variant,
            artifact_status=artifact_status,
            checks=checks,
            require_capture_artifacts=require_capture_artifacts,
            require_provider_artifacts=require_provider_artifacts,
            require_task_artifacts=require_task_artifacts,
        )

    summary = {
        "schema_version": "prefix-agbench-suite-verification-v1",
        "manifest_path": str(manifest_file),
        "suite_id": manifest.get("suite_id"),
        "ready": all(bool(check.get("ok")) for check in checks),
        "checks": checks,
        "artifact_status": artifact_status,
        "load_components": load_components,
        "requirements": {
            "capture_artifacts_required": require_capture_artifacts,
            "provider_artifacts_required": require_provider_artifacts,
            "task_artifacts_required": require_task_artifacts,
        },
        "prompt_safe_summary": True,
        "real_provider_metrics_available": False,
        "real_provider_metrics_note": (
            "This verification checks suite structure and local artifact presence. "
            "It does not run AutoGenBench or prove provider cached tokens, latency, cost, or task success."
        ),
        "autogenbench_compatibility_note": (
            "AutoGenBench 0.0.3 consumes OAI_CONFIG_LIST through autogenbench run. "
            "The generated model_config YAML files are for AgentChat/newer scenario templates that call "
            "ChatCompletionClient.load_component(config['model_config'])."
        ),
    }
    target = _write_json(summary_path, summary)
    return AgBenchSuiteVerificationResult(
        manifest_path=str(manifest_file),
        summary_path=str(target) if target is not None else None,
        summary=summary,
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Verify a generated AutoGenBench prefix suite manifest.")
    parser.add_argument("--manifest", required=True, help="suite_manifest.json generated by agbench_suite.")
    parser.add_argument("--summary", help="Optional prompt-safe verification summary JSON output.")
    parser.add_argument("--skip-component-load", action="store_true")
    parser.add_argument("--require-capture-artifacts", action="store_true")
    parser.add_argument("--require-provider-artifacts", action="store_true")
    parser.add_argument("--require-task-artifacts", action="store_true")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    result = verify_agbench_suite(
        manifest_path=args.manifest,
        summary_path=args.summary,
        load_components=not args.skip_component_load,
        require_capture_artifacts=args.require_capture_artifacts,
        require_provider_artifacts=args.require_provider_artifacts,
        require_task_artifacts=args.require_task_artifacts,
    )
    print(json.dumps(result.summary, ensure_ascii=False, sort_keys=True))
    return 0 if result.summary["ready"] else 1


def _check_manifest_shape(manifest: Mapping[str, Any], checks: list[dict[str, Any]]) -> None:
    _add_check(
        checks,
        name="manifest:schema_version",
        ok=manifest.get("schema_version") == "prefix-agbench-suite-manifest-v1",
        detail=str(manifest.get("schema_version")),
        next_step="Regenerate the suite with autogen_prefix_tree.agbench_suite.",
    )
    _add_check(
        checks,
        name="manifest:prompt_safe",
        ok=manifest.get("prompt_safe_manifest") is True,
        detail=str(manifest.get("prompt_safe_manifest")),
        next_step="Regenerate the suite; manifest must only contain paths and aggregate metadata.",
    )
    _add_check(
        checks,
        name="manifest:no_embedded_model_config",
        ok=not _contains_key(manifest, "model_config") and not _contains_key(manifest, "_config"),
        detail="model_config is not embedded" if not _contains_key(manifest, "model_config") else "model_config embedded",
        next_step="Do not store full model configs inside suite_manifest.json.",
    )
    _add_check(
        checks,
        name="manifest:pre_run_provider_metrics",
        ok=manifest.get("real_provider_metrics_available") is False,
        detail=str(manifest.get("real_provider_metrics_available")),
        next_step="A config suite should not claim provider metrics before benchmark/provider runs.",
    )


def _verify_variant_config(
    *,
    label: str,
    variant: Mapping[str, Any],
    checks: list[dict[str, Any]],
    load_components: bool,
) -> None:
    config_path = variant.get("config_path")
    if not isinstance(config_path, str) or not config_path:
        _add_check(checks, name=f"config:{label}:path", ok=False, detail="missing config_path")
        return
    path = Path(config_path)
    if not path.exists():
        _add_check(
            checks,
            name=f"config:{label}:exists",
            ok=False,
            detail=str(path),
            next_step="Regenerate the suite or restore the missing YAML file.",
        )
        return
    _add_check(checks, name=f"config:{label}:exists", ok=True, detail=str(path))
    try:
        config = _read_structured(path)
    except Exception as exc:  # noqa: BLE001
        _add_check(checks, name=f"config:{label}:readable", ok=False, detail=f"{type(exc).__name__}: {exc}")
        return
    model_config = config.get("model_config")
    _add_check(
        checks,
        name=f"config:{label}:model_config",
        ok=isinstance(model_config, Mapping),
        detail="present" if isinstance(model_config, Mapping) else "missing",
    )
    if not isinstance(model_config, Mapping):
        return
    _check_variant_semantics(label=label, variant=variant, model_config=model_config, checks=checks)
    if not load_components:
        return
    try:
        ChatCompletionClient.load_component(model_config)
    except Exception as exc:  # noqa: BLE001
        _add_check(
            checks,
            name=f"config:{label}:component_load",
            ok=False,
            detail=f"{type(exc).__name__}: {exc}",
            next_step="Check provider namespace, dependencies, and nested client config.",
        )
    else:
        _add_check(checks, name=f"config:{label}:component_load", ok=True, detail="loaded")


def _check_variant_semantics(
    *,
    label: str,
    variant: Mapping[str, Any],
    model_config: Mapping[str, Any],
    checks: list[dict[str, Any]],
) -> None:
    provider = model_config.get("provider")
    config = model_config.get("config") if isinstance(model_config.get("config"), Mapping) else {}
    if label == "baseline":
        _add_check(
            checks,
            name="config:baseline:not_wrapped",
            ok=provider != "autogen_prefix_tree.client.PrefixReorderClient"
            and provider != "autogen_prefix_tree.request_capture.RequestCaptureClient",
            detail=str(provider),
        )
    elif label == "capture":
        _add_check(
            checks,
            name="config:capture:provider",
            ok=provider == "autogen_prefix_tree.request_capture.RequestCaptureClient",
            detail=str(provider),
        )
        _check_path_matches(
            checks,
            name="config:capture:capture_log_path",
            actual=config.get("capture_log_path"),
            expected=variant.get("capture_log_path"),
        )
    elif label.startswith("plugin"):
        _add_check(
            checks,
            name=f"config:{label}:provider",
            ok=provider == "autogen_prefix_tree.client.PrefixReorderClient",
            detail=str(provider),
        )
        _check_path_matches(
            checks,
            name=f"config:{label}:telemetry_log_path",
            actual=config.get("telemetry_log_path"),
            expected=variant.get("telemetry_log_path"),
        )
        _add_check(
            checks,
            name=f"config:{label}:natural_language_segmentation",
            ok=bool(config.get("enable_natural_language_segmentation"))
            == bool(variant.get("natural_language_segmentation_enabled")),
            detail=str(config.get("enable_natural_language_segmentation")),
        )
        semantic_guard = config.get("semantic_guard")
        _add_check(
            checks,
            name=f"config:{label}:semantic_guard",
            ok=bool(isinstance(semantic_guard, Mapping)) == bool(variant.get("semantic_guard_enabled")),
            detail="present" if isinstance(semantic_guard, Mapping) else "absent",
        )
    elif label == "static_capture":
        _add_check(
            checks,
            name="config:static_capture:provider",
            ok=provider == "autogen_prefix_tree.request_capture.RequestCaptureClient",
            detail=str(provider),
        )
        inner = config.get("inner_client") if isinstance(config.get("inner_client"), Mapping) else {}
        _add_check(
            checks,
            name="config:static_capture:inner_static_client",
            ok=inner.get("provider") == "autogen_prefix_tree.static_client.StaticResponseClient",
            detail=str(inner.get("provider")),
        )


def _collect_artifact_status(
    *,
    label: str,
    variant: Mapping[str, Any],
    artifact_status: list[dict[str, Any]],
    checks: list[dict[str, Any]],
    require_capture_artifacts: bool,
    require_provider_artifacts: bool,
    require_task_artifacts: bool,
) -> None:
    for field, required in (
        ("capture_log_path", require_capture_artifacts),
        ("telemetry_log_path", False),
        ("provider_telemetry_path", require_provider_artifacts),
        ("task_results_path", require_task_artifacts),
    ):
        path_value = variant.get(field)
        if not isinstance(path_value, str) or not path_value:
            continue
        path = Path(path_value)
        exists = path.exists()
        size_bytes = path.stat().st_size if exists else 0
        artifact_status.append(
            {
                "variant": label,
                "field": field,
                "path": str(path),
                "exists": exists,
                "size_bytes": size_bytes,
                "required": required,
            }
        )
        if required:
            _add_check(
                checks,
                name=f"artifact:{label}:{field}",
                ok=exists and size_bytes > 0,
                detail=f"{path} ({size_bytes} bytes)" if exists else str(path),
                next_step="Run the matching benchmark/capture step before requiring this artifact.",
            )


def _check_path_matches(checks: list[dict[str, Any]], *, name: str, actual: Any, expected: Any) -> None:
    _add_check(
        checks,
        name=name,
        ok=str(actual) == str(expected),
        detail=f"actual={actual}; expected={expected}",
        next_step="Regenerate the suite so manifest and YAML paths match.",
    )


def _add_check(
    checks: list[dict[str, Any]],
    *,
    name: str,
    ok: bool,
    detail: str,
    next_step: str | None = None,
) -> None:
    check: dict[str, Any] = {"name": name, "ok": bool(ok), "detail": detail}
    if next_step and not ok:
        check["next_step"] = next_step
    checks.append(check)


def _contains_key(value: Any, key: str) -> bool:
    if isinstance(value, Mapping):
        for item_key, item_value in value.items():
            if item_key == key or _contains_key(item_value, key):
                return True
    elif isinstance(value, list | tuple):
        return any(_contains_key(item, key) for item in value)
    return False


def _load_json_mapping(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def _write_json(path: str | Path | None, value: Mapping[str, Any]) -> Path | None:
    if path is None:
        return None
    target = Path(path)
    if target.parent != Path("."):
        target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")
    return target


if __name__ == "__main__":
    raise SystemExit(main())
